<?php
// $Id: location.gw.inc,v 1.1 2009/04/16 09:47:13 juneeveek Exp $

// Guinea-Bissau

function location_province_list_gw() {
  return array('BF' => "Bafata Region",
    'BB' => "Biombo Region",
    'BS' => "Bissau Region",
    'BL' => "Bolama Region",
    'CA' => "Cacheu Region",
    'GA' => "Gabu Region",
    'OI' => "Oio Region",
    'QU' => "Quinara Region",
    'TO' => "Tombali Region");
}
