<?php
// $Id: location.jo.inc,v 1.1 2009/04/16 09:47:13 juneeveek Exp $

// Jordan

function location_province_list_jo() {
  return array('AJ' => "Ajlun",
    'AQ' => "Al 'Aqabah",
    'BA' => "Al Balqa'",
    'KA' => "Al Karak",
    'MF' => "Al Mafraq",
    'AM' => "'Amman",
    'TA' => "At Tafilah",
    'ZA' => "Az Zarqa'",
    'IR' => "Irbid",
    'JA' => "Jarash",
    'MN' => "Ma'an",
    'MD' => "Madaba");
}
