<?php
// $Id: location.bw.inc,v 1.1 2009/04/16 09:47:13 juneeveek Exp $

// Botswana

function location_province_list_bw() {
  return array('CE' => "Central",
    'GH' => "Ghanzi",
    'KD' => "Kgalagadi",
    'KT' => "Kgatleng",
    'KW' => "Kweneng",
    'NG' => "Ngamiland",
    'NE' => "North East",
    'NW' => "North West",
    'SE' => "South East",
    'SO' => "Southern");
}
