<?php
// $Id: location.mr.inc,v 1.1 2009/04/16 09:47:13 juneeveek Exp $

// Mauritania

function location_province_list_mr() {
  return array('AD' => "Adrar",
    'AS' => "Assaba",
    'BR' => "Brakna",
    'DN' => "Dakhlet Nouadhibou",
    'GO' => "Gorgol",
    'GM' => "Guidimaka",
    'HC' => "Hodh Ech Chargui",
    'HG' => "Hodh El Gharbi",
    'IN' => "Inchiri",
    'TA' => "Tagant",
    'TZ' => "Tiris Zemmour",
    'TR' => "Trarza",
    'NO' => "Nouakchott");
}
