<?php
// $Id: location.cg.inc,v 1.1 2009/04/16 09:47:13 juneeveek Exp $

// Congo

function location_province_list_cg() {
  return array('BO' => "Bouenza",
    'BR' => "Brazzaville",
    'CU' => "Cuvette",
    'CO' => "Cuvette-Ouest",
    'KO' => "Kouilou",
    'LE' => "Lekoumou",
    'LI' => "Likouala",
    'NI' => "Niari",
    'PL' => "Plateaux",
    'PO' => "Pool",
    'SA' => "Sangha");
}
