<?php
// $Id: linktocontent.install,v 1.1 2008/12/19 23:46:35 iikka Exp $

/*
* @file
* Linktocontent Module for Drupal 6.x (patched for FCKeditor)
*/

function linktocontent_uninstall() {
  variable_del('linktocontent_enabled_plugins');
  variable_del('linktocontent_plugin_weight');
  variable_del('linktocontent_registered_plugins');
  drupal_set_message(t('Linktocontent module successfully uninstalled'));
}
