<?php
// $Id: location.gq.inc,v 1.1 2009/04/16 09:47:13 juneeveek Exp $

// Equatorial Guinea

function location_province_list_gq() {
  return array('AN' => "Provincia Annobon",
    'BN' => "Provincia Bioko Norte",
    'BS' => "Provincia Bioko Sur",
    'CS' => "Provincia Centro Sur",
    'KN' => "Provincia Kie-Ntem",
    'LI' => "Provincia Litoral",
    'WN' => "Provincia Wele-Nzas");
}
