<?php
// $Id: location.sa.inc,v 1.1 2009/04/16 09:47:13 juneeveek Exp $

// Saudia Arabia

function location_province_list_sa() {
  return array('BH' => "Al Bahah",
    'HS' => "Al Hudud ash Shamaliyah",
    'JF' => "Al Jawf",
    'MD' => "Al Madinah",
    'QS' => "Al Qasim",
    'RD' => "Ar Riyad",
    'AQ' => "Ash Sharqiyah (Eastern Province)",
    'AS' => "'Asir",
    'HL' => "Ha'il",
    'JZ' => "Jizan",
    'ML' => "Makkah",
    'NR' => "Najran",
    'TB' => "Tabuk");
}
