<?php
// $Id: location.um.inc,v 1.1 2009/04/16 09:47:13 juneeveek Exp $

// United States Minor Outlying Islands

function location_province_list_um() {
  return array('BI' => "Baker Island",
    'HI' => "Howland Island",
    'JI' => "Jarvis Island",
    'JA' => "Johnston Atoll",
    'KR' => "Kingman Reef",
    'MA' => "Midway Atoll",
    'NI' => "Navassa Island",
    'PA' => "Palmyra Atoll",
    'WI' => "Wake Island");
}
