<?php
// $Id: location.ls.inc,v 1.1 2009/04/16 09:47:13 juneeveek Exp $

// Lesotho

function location_province_list_ls() {
  return array('BE' => "Berea",
    'BB' => "Butha-Buthe",
    'LE' => "Leribe",
    'MF' => "Mafeteng",
    'MS' => "Maseru",
    'MH' => "Mohale's Hoek",
    'MK' => "Mokhotlong",
    'QN' => "Qacha's Nek",
    'QT' => "Quthing",
    'TT' => "Thaba-Tseka");
}
