<?php
// $Id: location.lu.inc,v 1.1 2009/04/16 09:47:13 juneeveek Exp $

// Luxembourg

function location_province_list_lu() {
  return array('DD' => "Diekirch",
    'DC' => "Clervaux",
    'DR' => "Redange",
    'DV' => "Vianden",
    'DW' => "Wiltz",
    'GG' => "Grevenmacher",
    'GE' => "Echternach",
    'GR' => "Remich",
    'LL' => "Luxembourg",
    'LC' => "Capellen",
    'LE' => "Esch-sur-Alzette",
    'LM' => "Mersch");
}
