<?php
// $Id: location.li.inc,v 1.1 2009/04/16 09:47:13 juneeveek Exp $

// Liechtenstein

function location_province_list_li() {
  return array('V' => "Vaduz",
    'A' => "Schaan",
    'B' => "Balzers",
    'N' => "Triesen",
    'E' => "Eschen",
    'M' => "Mauren",
    'T' => "Triesenberg",
    'R' => "Ruggell",
    'G' => "Gamprin",
    'L' => "Schellenberg",
    'P' => "Planken");
}
