<?php
// $Id: location.zw.inc,v 1.1 2009/04/16 09:47:13 juneeveek Exp $

// Zimbabwe

function location_province_list_zw() {
  return array('BU' => "Bulawayo (city)",
    'HA' => "Harare (city)",
    'ML' => "Manicaland",
    'MC' => "Mashonaland Central",
    'ME' => "Mashonaland East",
    'MW' => "Mashonaland West",
    'MV' => "Masvingo",
    'MN' => "Matabeleland North",
    'MS' => "Matabeleland South",
    'MD' => "Midlands");
}
