<?php
// $Id: location.mu.inc,v 1.1 2009/04/16 09:47:13 juneeveek Exp $

// Mauritius

function location_province_list_mu() {
  return array('BR' => "Beau Bassin-Rose Hill",
    'CU' => "Curepipe",
    'PU' => "Port Louis",
    'QB' => "Quatre Bornes",
    'VP' => "Vacoas-Phoenix",
    'AG' => "Agalega Islands",
    'CC' => "Cargados Carajos Shoals (Saint Brandon Islands)",
    'RO' => "Rodrigues",
    'BL' => "Black River",
    'FL' => "Flacq",
    'GP' => "Grand Port",
    'MO' => "Moka",
    'PA' => "Pamplemousses",
    'PW' => "Plaines Wilhems",
    'PL' => "Port Louis",
    'RR' => "Riviere du Rempart",
    'SA' => "Savanne");
}
