<?php
// $Id: location.zm.inc,v 1.1 2009/04/16 09:47:13 juneeveek Exp $

// Zambia

function location_province_list_zm() {
  return array('CE' => "Central Province",
    'CB' => "Copperbelt Province",
    'EA' => "Eastern Province",
    'LP' => "Luapula Province",
    'LK' => "Lusaka Province",
    'NO' => "Northern Province",
    'NW' => "North-Western Province",
    'SO' => "Southern Province",
    'WE' => "Western Province");
}
